/**
 * The console's icon set: Phosphor, one family, one weight, imported through this module so a
 * screen never reaches for a second icon library or hand-rolls an SVG path.
 */
export {
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowsClockwise,
  Bell,
  Buildings,
  CaretDown,
  CaretRight,
  CaretUp,
  CaretUpDown,
  Megaphone,
  ChatCircleText,
  PushPin,
  Check,
  Coins,
  Copy,
  ClipboardText,
  Cloud,
  Cube,
  Database,
  GaugeIcon as Gauge,
  Gear,
  GraphicsCard,
  Hammer,
  HardDrives,
  Hourglass,
  Link as LinkIcon,
  List,
  LockKey,
  MagnifyingGlass,
  Moon,
  Package,
  Plus,
  Question,
  SignOut,
  SquaresFour,
  Sun,
  Tag,
  Tray,
  UserCircle,
  UsersThree,
  Warning,
  X,
} from '@phosphor-icons/react';
