#!/usr/bin/env bash
set -euo pipefail
# Generates GShare's secrets with openssl. Nothing has a default in the code or the images, so these
# have to be injected before anything starts.
#
# Generates: GSHARE_USER_JWT_SECRET (HS256), GSHARE_INTERNAL_JWT_PRIVATE_KEY (RS256) and its kid,
# POSTGRES_PASSWORD, and BOOTSTRAP_ADMIN_PASSWORD.
#
# Usage:
#   gen-secrets.sh           # write .env, refusing to overwrite an existing one
#   gen-secrets.sh --force   # overwrite .env
#   gen-secrets.sh --k8s     # print kubectl commands to create the Secrets, for production
#
# Never commit what this prints.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODE="env"
FORCE=0
for arg in "$@"; do
  case "$arg" in
    --k8s)   MODE="k8s" ;;
    --force) FORCE=1 ;;
    -h|--help) sed -n '3,8p' "$0"; exit 0 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }

# ── Random secrets ──
HS256_SECRET="$(openssl rand -hex 32)"
JWT_KID="k$(openssl rand -hex 4)"
DB_PASSWORD="$(openssl rand -base64 24 | tr -d '\n/+=' | cut -c1-24)"
ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -d '\n/+=' | cut -c1-18)"
RSA_PEM="$(openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 2>/dev/null)"

if [ "$MODE" = "k8s" ]; then
  # The proper answer is external-secrets backed by Vault or a KMS. What follows is direct injection,
  # for bootstrapping and private clusters.
  NS="${SYS_NS:-gshare-system}"
  cat <<EOF
# GShare secrets for namespace ${NS}. These are printed in the clear — mind your shell history.

# 1. HS256 signing key for user tokens, read as GSHARE_USER_JWT_SECRET
kubectl -n ${NS} create secret generic gshare-auth-token \\
  --from-literal=secret='${HS256_SECRET}' \\
  --dry-run=client -o yaml | kubectl apply -f -

# 2. RS256 signing key for the internal plane, stored as gshare-jwt-signing
cat <<'PEM' > /tmp/gshare-internal-jwt.pem
${RSA_PEM}
PEM
kubectl -n ${NS} create secret generic gshare-jwt-signing \\
  --from-file=private.pem=/tmp/gshare-internal-jwt.pem \\
  --from-literal=active_kid='${JWT_KID}' \\
  --dry-run=client -o yaml | kubectl apply -f -
rm -f /tmp/gshare-internal-jwt.pem

# 3. Initial super_admin password, read as GSHARE_BOOTSTRAP_ADMIN_PASSWORD. The email is set
#    separately.
kubectl -n ${NS} create secret generic gshare-bootstrap-admin \\
  --from-literal=password='${ADMIN_PASSWORD}' \\
  --dry-run=client -o yaml | kubectl apply -f -

# CloudNativePG manages the database password in gshare-pg-app. Running Postgres yourself, use
# POSTGRES_PASSWORD=${DB_PASSWORD}.
echo "[gen-secrets] done." >&2
EOF
  exit 0
fi

# ── .env mode ──
OUT="${ROOT}/.env"
if [ -f "$OUT" ] && [ "$FORCE" -ne 1 ]; then
  echo ".env already exists; pass --force to overwrite." >&2
  exit 1
fi

cat > "$OUT" <<EOF
# GShare .env, generated by gen-secrets.sh. Do not commit.

# ── Datastores ──
GSHARE_DATABASE_URL=postgresql+asyncpg://gshare:${DB_PASSWORD}@localhost:5432/gshare
GSHARE_REDIS_URL=redis://localhost:6379/0
POSTGRES_PASSWORD=${DB_PASSWORD}

# ── End-user authentication (HS256) ──
GSHARE_AUTH_ALLOW_LOCAL_PASSWORD=true
GSHARE_USER_JWT_SECRET=${HS256_SECRET}

# ── Bootstrap administrator ──
GSHARE_BOOTSTRAP_ADMIN_EMAIL=${GSHARE_BOOTSTRAP_ADMIN_EMAIL:-admin@example.com}
GSHARE_BOOTSTRAP_ADMIN_PASSWORD=${ADMIN_PASSWORD}

# ── Internal plane JWT (RS256) ──
GSHARE_INTERNAL_JWT_KID=${JWT_KID}
GSHARE_INTERNAL_JWT_PRIVATE_KEY="${RSA_PEM}"
# The api fetches this to verify its own tokens; locally and under Compose that is itself on :8080.
# On Kubernetes the chart points it at the in-cluster service.
GSHARE_INTERNAL_JWKS_URL=${GSHARE_INTERNAL_JWKS_URL:-http://localhost:8080/.well-known/gshare-internal-jwks.json}

# ── Session connect routing: the console and ingress domain of the registered cluster ──
GSHARE_SESSION_DOMAIN=${GSHARE_SESSION_DOMAIN:-gshare.example.com}
GSHARE_SESSION_URL_SCHEME=${GSHARE_SESSION_URL_SCHEME:-https}
EOF
chmod 600 "$OUT"
echo "[gen-secrets] wrote ${OUT} (chmod 600)" >&2
echo "[gen-secrets] initial administrator password: ${ADMIN_PASSWORD}" >&2
