---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gshare-operator
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gshare.io
  resources:
  - gpumodechanges
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gshare.io
  resources:
  - gpumodechanges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gshare.io
  resources:
  - gshareimagebuilds
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gshare.io
  resources:
  - gshareimagebuilds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gshare.io
  resources:
  - gsharesessions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gshare.io
  resources:
  - gsharesessions/finalizers
  verbs:
  - update
- apiGroups:
  - gshare.io
  resources:
  - gsharesessions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
